### ISSUE TITLE
Field clicking button covers bottom row

### ISSUE THREAD

**Issue by Noahverse** [Marirow/Strawberi-CSS#38]
Hello!
I'm on Safari on an iPhone XS (2436 × 1125 pixels) and the field clicking button covers the bottom row.
Two screenshots included because I thought it might be the URL bar "eating" some extra space but it's apparently not. Thank you!
<details>
<summary>Screenshots</summary>

![IMG_6168](https://github.com/Marirow/Strawberi-CSS/assets/167786970/3e5ddc29-8298-4677-af2a-d6fc6996f9cf)

![IMG_6169](https://github.com/Marirow/Strawberi-CSS/assets/167786970/abc3bf9e-c916-4e9e-b201-bc93c61e9474)
</details>

**Comment by Marirow** [comment]
Looks like Safari isn't playing nice with padding-bottom. (This is a known issue with the browser.)

What I'll do is change the padding to an ::after element so that Safari can't eat it so easily, and push that as a fix update. It might take me a day or two to resolve it.

**Comment by Marirow** [comment]
Should be fixed in 2.1.
